### ISSUE TITLE
Изучить инструменты для интеграционного тестирования

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#10]
Цель подзадачи: изучить инструменты при помощи которых можно будет создать интеграционные тесты для парсера

**Comment by sovietsolider** [comment]
Для интеграционных тестов подойдут библиотеки модульного тестирования, которые были указаны в [данной issue](https://github.com/moevm/MSE-2023-msm-doc_parser-18/issues/9). Парсер будет иметь интеграцию с БД, следовательно, можно проверять правильность запросов в указанных выше библиотеках, а также и саму запись данных в бд благодаря запросам к ней
