### ISSUE TITLE
[Баг] Полное зависание GUI во время парсинга PDF

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#13]
Во время демонстрации функционала программы был обнаружен баг. Причина известна, варианты исправления тоже. Баг не является критичным, поэтому в данный момент нет срочности его исправления.

**Comment by xaninam** [comment]
Баг был исправлен при помощи вынесения работы парсера в отдельный поток. Асинхронность позволяет вынести отдельные задачи из основного потока в специальные асинхронные методы и при этом более экономно использовать потоки. Ключевыми для работы с асинхронными вызовами в C# являются два оператора: async и await, они используются вместе для создания асинхронного метода.
Эти операторы были добавлены в метод ButtonStart_Click в Form.cs и его код стал таким:

private **async** void ButtonStart_Click(object sender, EventArgs e)
        {
            **await Task.Run(() =>**
            {
                if (ofd.FileName != "")
                {
                    Result = Parser.PDFToString(ofd.FileName);
                }
                else
                {
                    MessageBox.Show("Вы не выбрали файл!");
                }});
            RTBOutput.Text = Result;
        }
