### ISSUE TITLE
Изучить как работают Tabula и Camelot

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#16]
Цель подзадачи: изучить как работают данные библиотеки, возможно черпнуть из них вдохновения, а может они нам подойдут.

**Comment by Krauzer1121** [comment]
https://github.com/BobLd/tabula-sharp
https://github.com/BobLd/camelot-sharp

**Comment by lexapech** [comment]
Библиотеки работают схожим образом: 
Документ рендерится, а затем при помощи оптического распознавания выявляются вертикальные и горизонтальные линии таблиц, далее происходит поиск ячеек и парсинг текста в них.

Библиотека camelot использует устаревшую версию PdfPig, поэтому запустить её не удалось.

Библиотека Tabula предоставляет возможность детектирования таблицы и её парсинга.

Для детектирования есть варианты с оптическим распознаванием, на основе графических операций PDF и режим решетки.

В примере на гите используется режим на основе графических операций.

Это можно использовать для того, чтобы определить, есть ли вообще на странице таблица.

Для парсинга есть 2 алгоритма: базовый и решетка. Ниже приведен результат работы базового алгоритма, он использует расстояния между словами для поиска ячеек. Так как в документации расстояния небольшие, получается плохой результат.

![Image](https://user-images.githubusercontent.com/71723386/226745001-4f9d5727-c107-4854-98b7-3eb8b47fd805.png)

Второй метод использует линии таблицы для разделения ячеек(Lattice Mode)

Результат его работы выглядит так:

![Image](https://user-images.githubusercontent.com/71723386/226746268-dbe1411f-358b-4098-b92c-82c0efab6dc3.png)

Каждая таблица представлена отдельным объектом, в котором есть список строк, а в каждой строке - список ячеек.

Библиотека предоставляет сразу текст ячейки, но не позволяет контролировать его парсинг.
