### ISSUE TITLE
Изучить причину неправильно отображения символов при чтении pdf

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#17]
Цель подзадачи: понять почему символ считывает неправильно и потом также неправильно записывается в xml

**Comment by cyberc001** [comment]
Причина неправильного считывания символов с некоторых файлов документации заключается в том, что эти файлы используют специальные шрифты, которые имеют кодировку, отличную от любой существующей (UTF-8, ASCII, Windows-1251, другие кодировки кириллицы).
Похоже что это было сделано с целью сжатия файлов, т.к. в таком шрифте отсутствуют даже некоторые латинские символы (которые, видимо, не используются в документе):
![image](https://user-images.githubusercontent.com/69343281/226611317-8b7ef3c7-5069-4b50-b979-bfabdb2c7164.png)
![image](https://user-images.githubusercontent.com/69343281/226611422-7baa72bd-ed47-441b-a9e1-c6452ec8cd2b.png)
Это приводит к тому, что даже при правильном отображении документа в браузере / программе для чтения PDF внутренний текст документа не читаем ни в одной кодировке. Это можно увидеть, например, выделив фрагмент текста в браузере и вызвав контекстное меню. Опция "искать ... в ..." будет показывать внутреннее, нечитаемое представление символов.
![image](https://user-images.githubusercontent.com/69343281/226611959-e2c0bd5c-a5d3-4146-888e-37200152f8ea.png)

Решить эту проблему можно следующими способами:
- Найти всевозможные такие "сломанные" шрифты, вручную замаппить символы "кодировки" шрифта на символы UTF-8, затем при парсинге преобразовывать символы, напечатанные в таких шрифтах.
- Подключить библиотеку, которая извлекает шрифты из PDF-файла (PigPDF, к сожалению, хранит это в private полях в не совсем удобочитаемом виде), затем подключить ещё какую-нибудь библиотеку, которая распознаёт, каким Unicode-символам соответствуют глифы шрифтов.
