### ISSUE TITLE
Изучить формат БД

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#18]
Цель подзадачи: изучить и описать формат базы данных приведенной заказчиком

**Comment by sovietsolider** [comment]
Microsoft Access — реляционная система управления базами данных. Access не серверная БД, хранится в файле расширения .mdb. MS Access входит в состав MS Office.
Взаимодействие с C# реализовано следующим образом:
Необходимо определить пространство имен:
```cs
using System.Data.OleDb;
```
Само подключение к БД:
```cs
private OleDbConnection myConnection;
myConnection = new OleDbConnection("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=Workers.mdb;")
// открываем соединение с БД
myConnection.Open();
// закрываем соединение с БД
myConnection.Close();
```
SQL запросы к БД отправляются образом, представленным ниже:
```cs
string query = "SELECT w_name FROM Worker WHERE w_id = 1";
// создаем объект OleDbCommand для выполнения запроса к БД MS Access
OleDbCommand command = new OleDbCommand(query, myConnection);
textBox1.Text = command.ExecuteScalar().ToString();
```
Метод `ExecuteScalar()` выполняет команду и возвращает значение из первого столбца первой строки любого результирующего набора. Удобно при возвращении одного значения или подсчете строк, столбцов, значений и тд.
Метод `ExecuteNonQuery()` выполняет команду, но не возвращает вывода;
Метод `ExecuteReader()` выполняет команду и возвращает типизированный IDataReader;
IDataReader - интерфейс, представляющий результат, возвращаемый из БД. Подробнее можно почитать [здесь](https://learn.microsoft.com/ru-ru/dotnet/api/system.data.idatareader?view=net-7.0).
Пример использования `ExecuteReader()`:
```cs
string query = "SELECT w_name, w_position, w_salary FROM Worker ORDER BY w_salary";
// создаем объект OleDbCommand для выполнения запроса к БД MS Access
OleDbCommand command = new OleDbCommand(query, myConnection);
 
// получаем объект OleDbDataReader для чтения табличного результата запроса SELECT
OleDbDataReader reader = command.ExecuteReader();
// в цикле построчно читаем ответ от БД
while(reader.Read())
{
    // выводим данные столбцов текущей строки (3 столбца, индексы 0, 1, 2)
    Console.WriteLine(reader[0].ToString() + reader[1].ToString() + reader[2].ToString());
}
// закрываем OleDbDataReader
reader.Close();
```
Пример использования `ExecuteNonQuery()`:
```cs
string query = "INSERT INTO Worker (w_name, w_position, w_salary) VALUES ('Михаил', 'Водитель', 20000)";
// создаем объект OleDbCommand для выполнения запроса к БД MS Access
OleDbCommand command = new OleDbCommand(query, myConnection);
// выполняем запрос к MS Access
command.ExecuteNonQuery();
```
Полезные ссылки:
Про структуры System.Data (описание классов, методов и тд): https://learn.microsoft.com/ru-ru/dotnet/api/system.data?view=net-7.0
Хорошие примеры работы с MS Access на русском для чайников: https://vscode.ru/prog-lessons/ms-access-i-c-sharp-rabotaem-s-bd.html
