### ISSUE TITLE
Придумать как обнаруживать таблицу при парсинге pdf файла

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#19]
Цель подзадачи: понять и описать как можно парсить таблицу в pdf файле.

**Comment by Krauzer1121** [comment]
Можно воспользоваться идеями из библиотек Tabula и Camelot #16 или использовать их.

**Comment by lexapech** [comment]
Для парсинга таблиц предлагаю использовать библиотеку Tabula, так как она позволяет как определить присутствие таблицы на странице, так и распарсить её.
Для таблиц с рамкой, которые есть документации на новые приборы, лучше всего использовать парсер SpreadsheetExtractionAlgorithm, который определяет ячейки таблицы на основе разделяющих линий между ними. Он хорошо справляется с таблицами из документации.
 На выходе этого парсера получается список всех таблиц на странице. Каждая таблица содержит в себе список строк и ячеек, к которым уже можно обратиться.
В библиотеке предусмотрен парсинг текста внутри ячейки, но его нельзя никак настроить, поэтому я предлагаю использовать только координаты найденных ячеек и парсить внутренний текст собственными методами.
Для этого можно из всех символов на странице выбрать те, которые находятся внутри нужной ячейки и далее парсить их методом предложенным в #4 
В процессе тестирования был получен такой результат:


![Image](https://user-images.githubusercontent.com/71723386/226749943-5204e707-8602-4819-bdef-9d72cc169255.png)

Таблицы из структуры Table полученные из парсера были преобразованы в формат RTF для вывода в текстовом поле

Определение присутствия таблицы на странице пока не тестировал, но можно использовать предложенные в tabula детекторы.

В целом представленный на гите Tabula алгоритм справляется с нашей задачей 
(https://github.com/BobLd/tabula-sharp#lattice-mode---spreadsheetextractionalgorithm)
