### ISSUE TITLE
Добавить новый формат сохранения файла

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#21]
Цель подзадачи: при выборе в каком формате сохранять файл в интерефейсе, добавить формат выбора СУБД MS Access.

**Comment by xaninam** [comment]
Был добавлен формат СУБД MS Access при сохранении файла в интерефейсе. Для этого в фильтр имен файлов, которая определяет варианты, доступные в поле диалогового окна, была добавлена строчка:

sfd.Filter = "**Data base file|*.mdb**|XML|*.xml";


![Image](https://user-images.githubusercontent.com/71763721/227739822-ca72360b-57a2-4021-b40b-8f640c618497.png)
