### ISSUE TITLE
Добавить анимацию прогрузки в интерфейс парсера

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#23]
Цель подзадачи: добавить и зафикисировать анимацию прогрузки в интерфейс парсера.

**Comment by xaninam** [comment]
Для фиксации анимации при перемещении основной формы, был использован обработчик событий Window_LocationChanged, в котором координаты главного окна передаются всплывающему. 



        private void Window_LocationChanged(object sender, EventArgs e)
        {
            if (m_PreviousLocation.X != int.MinValue) 
                WaitForm2.Location = new Point(
                      WaitForm2.Location.X + Location.X - m_PreviousLocation.X,
                      WaitForm2.Location.Y + Location.Y - m_PreviousLocation.Y
                    );

            m_PreviousLocation = Location;
        }
