### ISSUE TITLE
Добавить вывод таблиц в XML файл

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#24]
Цель подзадачи: добавить вывод таблиц в xml файл. Пример оформления таблицы в XML брать отсюда.

**Comment by Krauzer1121** [comment]
https://www.w3schools.com/xml/tryxslt.asp?xmlfile=cdcatalog&xsltfile=cdcatalog

**Comment by cyberc001** [comment]
#26
