### ISSUE TITLE
Составить список всех методов, которые предоставляют информацию о содержимом PDF

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#4]
Цель подзадачи: 
Нужно описать входные и выходные данные всех существующих методов в библиотеке, которые дают какую-либо информацию о содержании PDF.

**Comment by lexapech** [comment]
PdfDocument PdfDocument.Open(string path, ParsingOptions options) – Считывает из файла документ

ParsingOptions – включить логгер, пароль для расшифровки

**Методы PdfDocument**

IEnumerable\<Page\> PdfDocument.GetPages() – Возвращает коллекцию страниц из документа

Page PdfDocument.GetPage(int pageNumber) – Извлекает из документа страницу с указанным номером(нумерация с 1)

**Методы**  **Page**

IEnumerable\<Word\> Page.GetWords(IWordExtractor wordExtractor) – Возвращает коллекцию слов на странице используя указанный wordExtractor

DictionaryToken Page.Dictionary – Необработанные данные соответствующие этой странице.

CropBox Page.CropBox – Возвращает видимую область страницы.

IReadOnlyList\<MarkedContentElement\> Page.GetMarkedContents() – Возвращаетсодержимое страницы оформленное в теги

String Page.Text – Возвращает текст со страницы в том порядке, в котором он находится во внутренней структуре документа.

соответствующих этому тегу.

Double Page.Width – Ширина страницы

Double Page.Height – Высота страницы.

IReadOnlyList\<Letter\> Page.Letters – Возвращает буквы на странице

IReadOnlyList\<IgraphicsStateOperation\> Page.Operations – Возвращает коллекцию графическихопераций в соответствии со спецификацией PDF.

**Методы**  **Word**

IReadOnlyList\<Letter\> Word.Letters – Возвращает буквы слова

PdfRectangle Word.BoundingBox – Возвращает прямоугольник, в который вписано слово

StringWord.Text – Возвращает слово в виде строки

TextOrientation Word.TextOrientation – Возвращает угол поворота текста.

String Word.FontName – Название шрифта

**Методы**  **Letter**

String Letter.Value – Возвращает строку, содержащую букву

FontDetails Letter.Font – Возвращает информацию о шрифте.

IColor Letter.Color – Возвращает цвет буквы

PdfPoint Letter.StartBaseLine – Возвращает координаты левого нижнего угла буквы

PdfPoint Letter.EndBaseLine – Возвращает координаты правого нижнего угла буквы

PdfPoint Letter.Location – Возвращает координаты левого нижнего угла буквы

string Letter.FontName – Название шрифта

double Letter.FontSize – Размер шрифта

PdfRectangle Letter.GlyphRectangle – Возвращает прямоугольник, в который вписана буква.

Int Letter.TextSequence – Возвращает номер операции отображения текста.

TextOrientation Letter.TextOrientation - Возвращает угол поворота текста.

Double Letter.Width – Ширина буквы.

**MarkedContentElement**

String MarkedContentElement.Tag – Возвращает тег.

IReadOnlyList\<Letter\> MarkedContentElement.Letters – Возвращает коллекцию букв

**Экстракторы текста**

String ContentOrderTextExtractor.GetText(Page page, [bool addDoubleNewline=false]) – Возвращает текст со страницы, разделенный на основании расстояний между буквами. addDoubleNewline разделяет параграфы пустой строкой.

NearestNeighbourWordExtractor(WordExtractorOptions wordExtractorOptions)

WordExtractorOptions – Настройка фильтра для поиска слов.

https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#advanced-case

IEnumerable\<Word\> NearestNeighbourWordExtractor.GetWords(IReadOnlyList\<Letter\> letters) – Возвращает слова, найденные на основе расстояния между буквами.

**Поиск абзацев**

DocstrumBoundingBoxes(DocstrumBoundingBoxesOptions pageSegmenterOptions)

DocstrumBoundingBoxesOptions – настройка алгоритма https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#docstrum-for-bounding-boxes-method

IReadOnlyList\<TextBlock\> DocstrumBoundingBoxes.GetBlocks(IEnumerable\<Word\> words) – Возвращает блоки текста, принимает на вход список слов на странице.

UnsupervisedReadingOrderDetector()

IReadOnlyList\<TextBlock\> UnsupervisedReadingOrderDetector.Get(IReadOnlyList\<TextBlock\> textBlocks) – сортирует блоки текста на странице.

**Методы**  **TextBlock**

IReadOnlyList\<TextLine\> TextBlock.TextLines – Возвращает строки в блоке текста.

PdfRectangle TextBlock.BoundingBox – Возвращает прямоугольник. В который вписан этот блок.

Int TextBlock.ReadingOrder – Номер блока на странице.

TextOrientation TextBlock.TextOrientation – Ориентация текста в блоке.

String TextBlock.Text – Весь текст из блока.

IReadOnlyList\<Word\> TextLine.Words – слова в строке

String TextLine.Text – весь текст строки.

TextEdgesExtractor(IEnumerable\<Word\> pageWords) – Возвращает края текста(нет документации)


Текст в документе представлен в виде набора букв с координатами, весь дальнейший анализ документа строится на этом.

Теги, которые возвращает Page.GetMarkedContents никак не связаны с границами абзацев и слов, то есть половина слова может быть в одном теге, а вторая – в другом.

**Comment by lexapech** [comment]
**Сравнение методов извлечения текста**
**Текущий метод**


![Image](https://user-images.githubusercontent.com/71723386/226735582-b13ee2b7-723a-4ed0-adf6-f0782a0295c1.png)

**ContentOrderTextExtractor**


![Image](https://user-images.githubusercontent.com/71723386/226735901-50de8ce8-a62e-4678-8d3c-c6687b29859c.png)

Метод работает неплохо, индексы находятся рядом со своими буквами, строки не перемешиваются

Минусы: 

1. Невозможно как-либо настроить способ парсинга

2. Принимает на вход страницу целиком, то есть не получится распарсить отдельно символы в ячейке таблицы.


**NearestNeighbourWordExtractor + DocstrumBoundingBoxes.DocstrumBoundingBoxesOptions +
UnsupervisedReadingOrderDetector**
Реализация: https://github.com/UglyToad/PdfPig/blob/master/examples/AdvancedTextExtraction.cs

![Image](https://user-images.githubusercontent.com/71723386/226736305-9157032f-ef05-4bcc-a367-8338aa9bc037.png)

NearestNeighbourWordExtractor работает чуть дольше, чем простые методы, но поддерживает настройку фильтра букв. 

DocstrumBoundingBoxes видит ячейки таблицы(но не все), при этом он находит блоки текста и внутри ячейки(там, где их быть не должно). Поэтому, например слово (ODD) съехало вниз(см. скрин). Поиск ячеек таблицы лучше организовать другими инструментами.

*NearestNeighbourWordExtractor + сортировка слов по y*
Реализация сортировки слов: 
https://github.com/UglyToad/PdfPig/blob/master/examples/OpenDocumentAndExtractWords.cs


![Image](https://user-images.githubusercontent.com/71723386/226736875-17dcbc2d-09f4-4df0-93cf-a9f4cd872781.png)

1. Можно настраивать как поиск слов через NearestNeighbourWordExtractor, так и их объединение в текст
2. Может принимать на вход список букв, что полезно, если нужно распарсить часть страницы(например, ячейку таблицы).
3. Индексы парсятся неплохо
4. Отдельно стоящие слова не уезжают вниз.

На данный момент предлагаю использовать этот способ, то есть 
1.	извлекать со страницы все буквы
2.	прогонять их через NearestNeighbourWordExtractor
3.	Полученные слова сортировать предложенным методом(https://github.com/UglyToad/PdfPig/blob/master/examples/OpenDocumentAndExtractWords.cs)

**Возможности по настройке NearestNeighbourWordExtractor**
NearestNeighbourWordExtractorOptions:

MaximumDistance – максимальное расстояние между двумя буквами в слове, если расстояние больше этого значения, то буквы принадлежат разным словам.

DistanceMeasure – Способ измерения расстояния между буквами, по умолчанию – Еваклидово расстояние.

DistanceMeasureAA - Способ измерения расстояния между буквами при углах поворота текста 0,90,180,270 градусов, по умолчанию – Манхэттенское расстояние.

Filter – Задает способ проверки принадлежности букв одному слову, принимает 2 буквы, возвращает true/false

FilterPivot – Задает фильтрацию букв, принимает одну букву, по умолчанию фильтруются пробелы.

GroupByOrientation – включает группировку по углу поворота.

Основной параметр – Filter, именно с ним нужно работать, если будут проблемы с генерацией слов.
