### ISSUE TITLE
Реализовать вывод таблицы в RichTextBox

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#50]
Цель: необходимо в richtextbox выводить таблицу с распаршенными параметрами. Формат таблицы обговаривали на созвоне (parametr, range, description). Если такое будет сложно реализовать в richtextbox или невозможно, то допускается заменить richtextbox на более удобное поле вывода для таблицы.

**Comment by cyberc001** [comment]
#55
