### ISSUE TITLE
Изучить вопрос добавления анимации прогрузки в GUI

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#6]
Цель подзадачи: изучить вопрос на тему того, как лучше и куда добавить анимацию прогрузки, во время парсинга.

**Comment by xaninam** [comment]
Изучив различные виды загрузок, я реализовала троббер во всплывающем окне, которое появляется во время работы парсера и исчезает сразу после вывода результата на экран.

![Image](https://user-images.githubusercontent.com/71763721/227335766-944d440e-0dcd-4f81-88c9-c8534a0e6518.png)
