### ISSUE TITLE
Создание адаптивного интерфейса

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#7]
Цель подзадачи: прописать в свойствах объектов GUI нужные параметры, чтобы интерфейс выгдел адекватно для использования при изменении размеров окна.

**Comment by xaninam** [comment]
Для того чтобы интерфейс стал адаптивным, для объектов были прописаны необходимые свойства.
Пример окна в полный экран:
![Image](https://user-images.githubusercontent.com/71763721/226134218-ee3f0051-8e06-4768-a342-3cd6a50d9323.png)

Пример растянутого горизонтально:
![Image](https://user-images.githubusercontent.com/71763721/226134219-8e88bd4f-5385-4eef-93ad-95875586e628.png)

Пример растянутого вертикально:
![Image](https://user-images.githubusercontent.com/71763721/226134217-29d462fd-29d3-4e77-820f-558115e677e7.png)

Пример минимально возможного окна:
![Image](https://user-images.githubusercontent.com/71763721/226134220-4151f469-9c59-431a-b406-08a3f41bcc99.png)
