### ISSUE TITLE
Изучить "тяжеловесность" методов библиотеки PigPDF

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#8]
Цель подзадачи: понять принцип работы каждого метода для получения информации о содержимом PDF.

**Comment by Krauzer1121** [comment]
После составления списка методов и их входных и выходных данных, нужно понять насколько вычислительно сложен каждый метод. Т.е. понять принцип его работы.

**Comment by lexapech** [comment]
Самые вычислительно сложные методы - GetPages и NearestNeighbourWordExtractor.GetWords

Все остальные методы сравнительно легкие.

От GetPages избавиться никак не получится, так как именно он выполняет чтение документа и поиск символов на страницах.

NearestNeighbourWordExtractor.GetWords проверяет все символы на страницы между собой и ищет радом стоящие. Его можно не использовать, но тогда не будет возможности парсить часть страницы и настраивать генерацию слов. При парсинге всего документа этот метод работает примерно 2.5 секунды. 

Суммарно парсинг документации на 400 страниц занимает примерно 4 секунды.

![Image](https://user-images.githubusercontent.com/71723386/226738471-e1a0726c-b2b0-42cc-a6aa-de8d269d62ce.png)
