### ISSUE TITLE
Изучить инструменты для создания unit тестов

### ISSUE THREAD

**Issue by Krauzer1121** [moevm/MSE-2023-msm-doc_parser-18#9]
Цель подзадачи: изучить инструменты при помощи которых можно будет создать unit тесты для парсера

**Comment by sovietsolider** [comment]
# Библиотеки C# для unit-тестирования
## MS Test
Фреймворк юнит-тестирования от Microsoft, который по умолчанию включен в Visual Studio и который также можно использовать с .NET Core. Есть возможность создать отдельный проект с данной библиотекой. 
Импорт библиотеки происходит следующим образом:
```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;
```
Сами тесты определяются при помощи атрибутов TestClass и TestMethod, например:
```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace BankTests
{
    [TestClass]
    public class BankAccountTests
    {
        [TestMethod]
        public void TestMethod1()
        {
        }
    }
}
```
В тестовых методах для проверки полученных результатов с ожидаемыми используются методы класса Assert:
```cs
Assert.IsTrue(...)
Assert.IsFalse(...)
Assert.AreEqual(...)
```
Полное описание класса со всеми методами и их атрибутами можно найти [здесь](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert?view=visualstudiosdk-2022)

## xUnit.net

Библиотека, по функционалу схожая с MS Test. В данной библиотеке класс, хранящий тест-кейсы не помечаются отдельным атрибутом, а сам метод(тест кейс) имеет атрибут [Fact]. Пример:
```cs
namespace namespaceName
{
  public class TestClassName
  {
    [Fact]
    public void TestCase1()
    {
      //testing
    }
  }
}
```
В тестовых методах для проверки полученных результатов с ожидаемыми используются методы класса Assert:
```cs
Assert.Is.EqualTo(...)
Assert.Is.Not.EqualTo(...)
Assert.Is.Empty(...)
Assert.Is.False(...)
```
Полное описание класса со всеми методами и их атрибутами можно найти [здесь](https://xunit.net/docs/comparisons)  
Предлагаю использовать MS Test, библиотека встроенная, имеет лаконичное объявление тестов(субъективно), но особой разницы между библиотеками нет.
